### ISSUE TITLE
Error Running Test Data

### ISSUE THREAD

**Issue by ebwinter95** [MaestSi/UMInator#1]
Hi, I am encountering this command error "[E::stk_trimfq] failed to open the input file/stream." when attempting to run the test command. 

I downloaded the Zymo data and adjusted all of the paths accordingly yet I am getting an error cause: Session aborted -- Cause: Process `candidateUMIsExtraction (1)` terminated with an error exit status (1)

Any help would be much appreciated! Thank you

**Comment by MaestSi** [comment]
Hi, could you please report the full command that you used, and edits you did to UMInator.conf file (if any)?
My guess is that either you failed to specify the correct path to the fastq file or you forgot to mount the relevant I/O directories.
Thanks,
SM

**Comment by ebwinter95** [comment]
I made no changes to the .conf file but here is the run command I used, in the meantime I will try reinstalling and remounting: 

nextflow -c /oldhome/evan/UMInator/UMInator.conf run /oldhome/evan/UMInator/UMInator.nf \
--FW_adapter="CAAGCAGAAGACGGCATACGAGAT" \
--RV_adapter="AATGATACGGCGACCACCGAGATC" \
--FW_primer="AGRGTTYGATYMTGGCTCAG" \
--RV_primer="CGACATCGAGGTGCCAAAC" \
--fastq_files=/oldhome/evan/UMI_collapsing_testing/test_reads.fq \
--results_dir=/oldhome/evan/UMI_collapsing_testing/output/ \
--minQ=7 \
--minLen=3000 \
--maxLen=6000 \
--min_UMI_freq=10 \
--scripts_dir=/oldhome/evan/UMInator/scripts/ \
--medaka_model=r941_min_high_g330 \
-profile docker

**Comment by MaestSi** [comment]
Just remember to edit line 178 of UMInator.conf from
`containerOptions = '-v /home:/home'`
to
`containerOptions = '-v /home:/home -v /oldhome:/oldhome'`
to make both /home and /oldhome directories accessible to the container.
SM

**Comment by ebwinter95** [comment]
That edit made all the difference. Thank you!

**Comment by MaestSi** [comment]
Great!
Best,
SM
