### ISSUE TITLE
Error while running Zymo test data

### ISSUE THREAD

**Issue by jayyu-0528** [MaestSi/UMInator#2]
Hello Simone,

Thank you so much for developing and sharing this software package.  I am a new user trying to use UMInator to analyze Nanopore long-read UMI-barcoded data. 

Because my lab does not have a Linux machine, I am using a Ubuntu 22.04 virtual machine on Amazon Web Services (AWS).  I found that the AWS virtual machines do not support KVM, which is required for Docker, so I end up chosing to install Singularity. 

After installing NextFlow, Singularity and UMInator (on a brand new Ubuntu 22.04 image; see the attached file for the complete list of commands that I used to install these softwares), I tried to run the pipeline test with the Zymo test data from Karst. et al., as described in the Readme documentation.   

For the run, I did not modify the UMInator.conf file at all, and use the following command to start the pipeline:

![image](https://github.com/MaestSi/UMInator/assets/98508513/501656f6-06e7-472e-a8ad-bb8a03802708)

But the run ended with the following console output, and error message: 

![image](https://github.com/MaestSi/UMInator/assets/98508513/256402b9-80e1-4800-a20c-66a70edc79a1)

After the error, I checked the directories and found that " /home/ubuntu/UMInator/work/42/54cc6ad5bbeff080b2a351fbbaf9f9 " was created, but there is no content in the directory.   Re-running the same command resulted in the same error, but with different sub-directory name under  /work/.   e.g., not "42", but "e9", "4f", and so forth.

If you have any clue on why this error is occurring, would you mind letting me know?   
Will be very grateful!

Best,
Jay

P.s. All the commands that I used to install NextFlow, Singularity and UMInator on a brand new Ubuntu 22.04:
[MaestSi UMInator installation procedure.docx](https://github.com/MaestSi/UMInator/files/14496410/MaestSi.UMInator.installation.procedure.docx)

Java version: 19.0.2
Go version: 1.22.0
Singularity version: 3.10.5

**Comment by MaestSi** [comment]
Hi,
at line 112 of UMInator.conf file, you should edit:
`executor = 'pbspro' // set to 'local' if you are not using a queue management system`
 to:
`executor = 'local'`
 This is required to prevent submitting jobs with pbspro jobs scheduler.
Best,
SM

**Comment by jayyu-0528** [comment]
Hi Simone,

The error was resolved following your suggestion.   Thank you so much!   Looking forward to running our own nanopore data with the pipeline!

Best,
Jay
