### ISSUE TITLE
Readsfilter

### ISSUE THREAD

**Issue by MAXINELSX** [MaestSi/UMInator#5]
HI, sorry for bothering you again;
When I tried with the actual data
I just changed the line 178 with the right dir containerOptions = '-v /home:/home -v /autofs/tong1/LSX/lishuxian/lishuxian/202403-UMI-16S/fastq/:/autofs/tong1/LSX/lishuxian/lishuxian/202403-UMI-16S/fastq/'

My code is 
(env_nf) lishuxian@tong2:~/UMInator$ nextflow -c ~/UMInator/UASBUMInator.conf  run ~/UMInator/UMInator.nf -bg --FW_adapter="GGAATCACATCCAAGACTGGCTAG" --RV_adapter="AGRGTTYGATYMTGGCTCAG" --FW_primer="AGRGTTYGATYMTGGCTCAG" --RV_primer="RGYTACCTTGTTACGACTT" --fastq_files="/autofs/tong1/LSX/lishuxian/lishuxian/202403-UMI-16S/fastq/UASB_Nanopore.fastq" --results_dir=/autofs/tong1/LSX/lishuxian/lishuxian/202403-UMI-16S/fastq/UASB_Nanopore  --minQ=7 --minLen=600 --maxLen=2000  --min_UMI_freq=3 --maxF=10 --scripts_dir="$HOME/UMInator/scripts" --medaka_model=r10_min_high_g340 -profile docker
(env_nf) lishuxian@tong2:~/UMInator$ N E X T F L O W  ~  version 23.10.1
Launching `/home/lishuxian/UMInator/UMInator.nf` [drunk_almeida] DSL2 - revision: b6a013ff48
[0f/fe1084] Submitted process > readsFiltering (1)
(env_nf) lishuxian@tong2:~/UMInator$ ERROR ~ Error executing process > 'readsFiltering (1)'

Caused by:
  Process `readsFiltering (1)` terminated with an error exit status (1)

Command executed:

  mkdir -p /autofs/tong1/LSX/lishuxian/lishuxian/202403-UMI-16S/fastq/UASB_Nanopore
  mkdir -p /autofs/tong1/LSX/lishuxian/lishuxian/202403-UMI-16S/fastq/UASB_Nanopore/readsFiltering
  mkdir -p /autofs/tong1/LSX/lishuxian/lishuxian/202403-UMI-16S/fastq/UASB_Nanopore/readsFiltering/UASB_Nanopore
  
  #filter reads
  zless /autofs/tong1/LSX/lishuxian/lishuxian/202403-UMI-16S/fastq/UASB_Nanopore.fastq | NanoFilt -q 7 --length 600 --maxlength 2000 > /autofs/tong1/LSX/lishuxian/lishuxian/202403-UMI-16S/fastq/UASB_Nanopore/readsFiltering/UASB_Nanopore/UASB_Nanopore_filtered.fastq

Command exit status:
  1

Command output:
  (empty)

Command error:
  WARNING: Your kernel does not support swap limit capabilities or the cgroup is not mounted. Memory limited without swap.
  ERROR:root:End of file without quality information.
  Traceback (most recent call last):
    File "/opt/conda/envs/UMInator_supp_env/lib/python3.10/site-packages/nanofilt/NanoFilt.py", line 44, in main
      filter_stream(args.input, args)
    File "/opt/conda/envs/UMInator_supp_env/lib/python3.10/site-packages/nanofilt/NanoFilt.py", line 72, in filter_stream
      for rec in SeqIO.parse(fq, "fastq"):
    File "/opt/conda/envs/UMInator_supp_env/lib/python3.10/site-packages/Bio/SeqIO/Interfaces.py", line 72, in __next__
      return next(self.records)
    File "/opt/conda/envs/UMInator_supp_env/lib/python3.10/site-packages/Bio/SeqIO/QualityIO.py", line 1123, in iterate
      for title_line, seq_string, quality_string in FastqGeneralIterator(handle):
    File "/opt/conda/envs/UMInator_supp_env/lib/python3.10/site-packages/Bio/SeqIO/QualityIO.py", line 945, in FastqGeneralIterator
      raise ValueError("End of file without quality information.")
  ValueError: End of file without quality information.
  Traceback (most recent call last):
    File "/opt/conda/envs/UMInator_env/bin/NanoFilt", line 8, in <module>
      sys.exit(main())
    File "/opt/conda/envs/UMInator_supp_env/lib/python3.10/site-packages/nanofilt/NanoFilt.py", line 44, in main
      filter_stream(args.input, args)
    File "/opt/conda/envs/UMInator_supp_env/lib/python3.10/site-packages/nanofilt/NanoFilt.py", line 72, in filter_stream
      for rec in SeqIO.parse(fq, "fastq"):
    File "/opt/conda/envs/UMInator_supp_env/lib/python3.10/site-packages/Bio/SeqIO/Interfaces.py", line 72, in __next__
      return next(self.records)
    File "/opt/conda/envs/UMInator_supp_env/lib/python3.10/site-packages/Bio/SeqIO/QualityIO.py", line 1123, in iterate
      for title_line, seq_string, quality_string in FastqGeneralIterator(handle):
    File "/opt/conda/envs/UMInator_supp_env/lib/python3.10/site-packages/Bio/SeqIO/QualityIO.py", line 945, in FastqGeneralIterator
      raise ValueError("End of file without quality information.")
  ValueError: End of file without quality information.

Work dir:
  /home/lishuxian/UMInator/work/0f/fe10847a7e8c16b898c4cc7f065278

Tip: view the complete command output by changing to the process work dir and entering the command `cat .command.out`
**But I manually checked **
(env_nf) lishuxian@tong2:~/UMInator$ tail  /autofs/tong1/LSX/lishuxian/lishuxian/202403-UMI-16S/fastq/UASB_Nanopore.fastq
+
ISSGJJNKGSJEEFJ<<<<=@@B9999;ISKSSIMNSKGSSSHJLGHSISSSISGJFFJSH9888943440'%%$%&'+,+++./--.??B@A@CEEBD??@ACCCE9899FCJLOMKFSHGSJGJSKLGKPSLSHKQSPFSNHSGHFSJSS?;:261'''*558?@@?HRGLSSJMDEDDGEKKMGJIRMGGOMSKMKSSLJDNJJSPHJHFKGHSIMFHJKMSGSSLJKSHHJSJMIDHDC:600/--..:=?DCCGSKHEEGHE>@@@BAGJKGEKIRGIFFSIIKFOSSMSNMSMKB;;4)((((56=FKRLSFEFFEGFH=554)(((*+>EHJLLJIIKISNGLIGGA==<>?FJOSSSKGJSJFKFDC;..334**+DLLSHFG54446>??@JIHFHSEKHSJEDDFDGKGJOFEEHFSGKGJSIIHLLIHFFHEEFEKEGCFFEFGSGPGGLGLLFHPKRLHJHIKSRHQGGIIQHFJJLLRSIHJNMGIISHGIGMKLHKC???@?I22222/.--.)''&&()*AEIILIGKKPFJNSDSGEHESGISRNOGSHSKSSSHGISHKJSJMOCCGGHOSSOISKKJJKJMSSHHMGRLILSKGEFDGGCC<<=CGJNNJFEHEEGSSPFIHF32222ISA@@@CGSHLSHQLKDCBCBF>KSHSSSSJFSIHHEHKJISRGHIJSNIGIJJFFCIESIFSSSLKKSOKHISHGMGGSKISJLSFFD<6../2CEECEGKNFHGDDDFIGJSGISLGIIQJ==<<=74(%%%&'(+/09?AGIHHKSGKFFBBBBA@@94454,///27CCBENHJFEC@@33*'&'&
@9a18e921-d43d-4c2d-9135-f5a2ef68bb84 runid=bd913b89e2ef2db9cbf43a7abb011d89c79b0aee read=62865 ch=2559 start_time=2024-03-27T11:41:43.861968+08:00 flow_cell_id=PAU34770 protocol_group_id=20240326-ZYL-UMI-16S sample_id=no_sample barcode=barcode03 barcode_alias=barcode03 parent_read_id=9a18e921-d43d-4c2d-9135-f5a2ef68bb84 basecall_model_version_id=dna_r10.4.1_e8.2_400bps_sup@v4.2.0
AATGATACGGCGACCACCGAGATCAGGTGACGCATAGCATTTGGTTACCTTGTTACGACTTCACCCCAGTCATGAATCTCACCGTGGCAAGCGCCCCCCTCGCGGTTAGGCTACCTGCTTCTGGTGAAACCCACTCCCATGGTGTGACGGGCGGTGTGTACAAGACCCGGGAACGTATTCACCGCGGCATGCTGATCCGCGATTACTAGCGATTCCGACTTGGCGGATCGAGTTGCAGACTCCGATCCGGACTACGATCGGCTTTGCAGGGATTGGCTCCGCATCGCTGCTTGGCAACCCTCTGTACCGACCATTGTATGACGTGTGAAGCCCTACCCATAAGGGCCATGAGGACTTGACGTCATCCCCACCTTCCTCCGGTTTGTCACCGGCAGTCTCACTAAAGTGCCCAACCAAATGATGGCAATCCATGGCAGAGGGTTCGCTGCGTTTAGGGACTTAACCCAACATCTCACGACACGAGCTGACGACAGCCATGCAGCACCTGTGTTCCGGTTCCCTTTCGGGCACCCCCGGCTCTTCACCCAGGATTCCGGACATGTCAAGGGTAGGTAAGGTTTTTCGCGTTGCATCGAATTAATCCACATCATCCACCGCTTGTGCGGGTCCCCGTCAATTCCTTTGAGTTTTAATCTTGCGACCGTACTCCCCAGGCGGCGAACTTCACGCGTTAGCTACGGTACTAAAGAAGTCTCCTTCCCCAACACCTAGTTCGCATCGTTTAGGGCGTGGACTACCAGGGTATCTAATCCTGTTTGCTCCCCACGCTTTCGTGCATGAGCGTCAGTGTCGACCCAGGGGGCTGCCTTCGCCATCGGTGTTCCTCCACATCTCTACGCATTTCACTGCTACACGTGGAATTCCACCCCCCTCTGCCGCACTCAAGTCTTGCAGTCACAAGCGCAGTTCCCAGGTTAAGCCCGGGGATTTCACACCTGTACAAAACCGCCTGCGCACGCTTTACGCCCAGTAATTCCGATTAACGCTCGCACCCTACGTATTACCGCGGCTGCTGGCACGTAGTTAGCCGGTGCTTCTTCTTCCGGTACCGTCATCCACACCAGGTATTAGCTGGCGCGATTTCTTCCCGGCCGAAAGAGCTTTACAACCCGAAGGCCTTCTTCACTCACGCGGCATGGCTGGATCAGGGTTGCCCCCATTGTCCAAAATTCCCCACTGCTGCCTCCCGTAGGAGTCTGGGCCGTGTCTCAGTCCCAGTGTGGCGGGCCGTCCTCTCAGACCCGCTACGGATCGTCGCCTTGGTAGGCCTTTACCCCACCAACTAGCTAATCCGACATCGGCCGCTCCTATAACACGAGGTCTTGCGAGCCCCCGCTTTCTCCCTCAGGACGTATGCGGTATTAGCCTACCTTTCGATAGGTTATCCCCCATTACAGGACACGTTCCGATGCATTACTCACCCGTTCGCCACTCGCCACCCAGTTGCCCGTGCTGTTCCGTTCGACTTGCATGTGTAAAGCATCACCAGCGTTCAATCTGAGCCGGAGTGAACGTCTCTGTCGCTCATGCTACCGCTAGCCAGTCTTGGATGTGATTCCA
+
PGSIFHFOGHLFGGDFKSKPREHJSHHPOFJFHLFDCDEEGHHSJIJIIRJHOKHKERJLJSMGISLGFLNKSSMHSFGONOHHJKISJGISSRKHIJNHJKFIHSHFHEJIKGJSJSJIHJKKISKCEGFIHSHFGD@DMOMKKSQSHINF===<<:50001:::=816IHHQSMIFJHFIHGHEJSKGJIJ@@AA@DC44))(()---.0::;SDDBG:***))0*)))++46?AKRGNGSIOSSSMHHMFC?//.77DDDEEHF><998843334DD??>ECRHHQSSGHGSEKPGISHMFLHHGKGSLGSSISRSKHHIJSSHPIJRKHKJNISEKIFJIIOQEMJSHLKFSHFESA@)((()156CLKGKNHHKDMGMSFFJNGHHLKIFLKG32,++,,89:GDGCIJIHHHE;::855101&&&&&&&(()))006666=?A877535556DCA@@AFHFGENHSKKLJIJKGKFFHGKHSHMGHFHLHHKIEBEBGFFLPMFSQLLFFDERNC>@HDDSLK@A??;8&&&&+=0+++8613AFDIESHGJJHGHSDLNLJMSGGIFDEPEDGQSKSILSSSNIGG66666BEEGHGOFKGHMHHISSHSIHSDFEI@<;;;-,,,,BDFCFHSGFG@@==BDB:7543445FGJHFJISJFDC?<CDELGSJISJSOSGDGDFFCBAAECLMGJGSSDGJGJSSFEHSSOJCFEDBGGGGGDEFBFFIFJHFEFFHFISIKLGGGFMHDCCBFIJKHHEHDEDDMGGKMIBDGFGQMLJJKIPHOSOHSOHGFGKHSMJJJIMISJQLGCABBDSKHSSSF<99:HHSHSGMJFFFDKJMHIHFNIKMHSKSMISKKKHGGJHDEDDGGHPSHFFFSGSCSEHHEFEFKLJSKGGNLEIHHGHISIGHFEEHGDGERA@A?@F910111FE><=<6HLHNSFGI9966666::::BEEHMGSKPNSSSFDGDIKQEFSSKKSJGFJJFKIFIHFFGKSKHHSSQJSSSLPIGFSFHIGIIHHNGHGIRJEDDCECKJHFIFKIHSKIHJ@@@@AADLEFKJHHFFSDGCKGFIEHBEIMKEFEEEHJJHLHISSLJDH544:3GELHC==DKOFMIJ87777ISMOJIHSMKJIFSFQSNKPGGGMIGEEEEGDFIFESJSHSMO=<:82-/CGCFFFFFGGFFFJMNIHGFKGIGHLKGF<FHISLJDCA;;;DSJNJEHFDCCGIFIHJIKKIIJGJMHFGSSSPKHBBJGIHSKJJJEDGOHIOFJGEIFONKGOEEMDHESEESS1/HDFEHDCCDDEHJKGSNKFFEILJSHSHSFIFICGFCHEFEHKFHLEDHFLJELSEABCEDBDGEFA@98779;;8567799ABB?>??AFEFEMMJNEGDCFGFGHDCFA@ACCBECFEEFFFDCDFDDEDCGECDBABDEEFFEGCDDGFBBA:----/4.(+**,-.*),,-860(('''.=??BCHGHDDDE@;+***)&&&%%&&&;;>@5554..,,,---''''$$$$&(()*+,-*++++:=;;;;;====94454499HFGDFDCCCBIDCH=
@11e37d54-5662-4c83-bd4e-922b62a820d0 runid=bd913b89e2ef2db9cbf43a7abb011d89c79b0aee read=62871 ch=2559 start_time=2024-03-27T11:41:47.861968+08:00 flow_cell_id=PAU34770 protocol_group_id=20240326-ZYL-UMI-16S sample_id=no_sample barcode=barcode03 barcode_alias=barcode03 parent_read_id=11e37d54-5662-4c83-bd4e-922b62a820d0 basecall_model_version_id=dna_r10.4.1_e8.2_400bps_sup@v4.2.0
AATGATACGGCGACCACCGAGATCTGTCATGTTAAATTGTGTAGTTACCTTGTTACGACTTAGTCCCAGTCACCGGTCTCACCGTCGGCCGCCGCCCTTTGCGGTTAGCTAAGCGGACTTCGGGTGCTCCCAGCTCCCATGACTTGACGGGCGGTGTGTACAAGGCTCAGGAACACATTCACCGCGCCATGGCTGATGCGCGATTACTAGCGATTCCAACTTCATGAGTGGGTTCAGAATTCCAATCTGAACTGGGCCCGGTTTTCTGCGATTTGCTCCACCTCACGGTCTCGCCTCGCTCTGTACCGGGCATTGTAGTACGTGTGATACCCCTGGGCATAAGGGCCATGATGACTTGACGTCGTCCCCACCTTCCTCCGGCTTAACGCCGGCAGTCTCGCTAGAGTTCCCGGCATGACCCGCTGGCAACTAACGACAAGGGTTTCGCTCGTTAAGGGACTTAACCCGACACTTCACAGCACGAGCTGACGACAGCCATGCAGCACCTGTGCACGTTTCACCCGAAGGCAGATTACTCGGCTTTCACCAAGACCATCCGTGCATGTCAAACCCAGGTAAGGTTCTTCGCGTTGCTTGGATTAAATCCACATACTCCACCGCTTGTGTGAGCCCCCGTCAATTCCTTTGAGTTTTAGCCTTGCGGCCGTACTCCCAGGCGGTGCACTTGACGTTTTCCTTCGGCACGATCGAGGTCAGACTCTCTCGTACCTAGTGCACATCGTTTACAGCGTGGACTACCAGGGTATCTAATCCTGTTTGCTCCCCACGCTCTCGCGTCTCAGCGTCAGGACAGGCCCAGTGACCCGTTTTCACCACCGGCGTTCCGTGTGATATCTACGCATTTCACCGCTCCACCACACGTTCCGGTCACCTCTACCTGCCTCAAGAGCGGCGGTTTCCCCTGCAATTCCCCGGTTGAGCCGGGGGCTTTCACAGAAGACCTGCCGCCCCGCCTACACGCGCTGTAAGCCCAGTGATTCCGATCAACGCTTCCCCCTACGTATTACCGCGGCTGCTGGCACGAAGTTAGCCGGGGCTTACCTCCGGGGCCGATCATTGTGTTTCTGACCCCTGACAGCAGTTTACATCCCGAAGGACTTCCTCCTGCACGCGGCGTCGCTCCGTCAGGCTTGCGCCCATTGCGAGATTTCGTTGCTGCAGCCACCCGTAGGTGTCCGGACAGTGTCTCAGTTCCGATGTGCCGGGTCATGCTCTCACACCCGGTACCCGTCGAAGCCTTGGTGAGCCGTTACCTCACCAACTAGCTGATAGGGAAAGGACCGATCCGGGACCGTCGGAGCTTTGCCCGCAAGGCCATGCGACCTCGCGGGGTCATCGGGTATTACCGGCGCTTTCGCAAAGGGTTGCCCCTGCCGCTATCCCCAAGTACCGGGTACGTTATCCTTCCATTCCTCACCCGTCCGCCACTATGCATGTATTGCTACATGCATCGTTCGACTTGCATGCTTTAGCCACGCCGCCAGCGTTCGATCTGAGCCAGGATCAAACTCTCCGCAAGCCATCACAGTCCTAGCCAGTCTTGGATGTGATTCCA
+
CIIDCHDGOIEEDEFJC3...35..1,++,1>@?@AJJMIJHLFSGIHGIGSHG>?JSHF@1000..,0001BLHGSHJSSNSKHHDDGE?>>2221)./'+CIGIKSJGRKJIGJIKKIIHMHIJJHKOGKHEFFFA>>KOHFKMSKHMISLSGKSHKDEEFFEFIICDCBGSFHHFHLKSJSMLEKFGIFNNSOHSSILOSILJIDDEGCCEDDFB@<?8.-,*('(),-/931///.//01<555558BCDCCGEKGKFJGD@@?CAIFKFFIIEF@@HF???GSGKJPIKSOJJLRKLFGFFHEHFDFDGE@4--11111:>AB><<<5*1127JHGFDEIHHHSOHGSLENLKSKKQHKFOSLSJMSDC88,,JDDIRK44444JFGIFEGGFSHSI?>@?BE=<0+-CEGFISHFHFGSSHHJFECBEDEEGGGFSSSJSIGIC=AC?AHGISIGJGNG?>>=>CEBECEIFGDEFHSHFSHKSGGF><;<ISGGHHHFGFKFNSSSSEEIIQQSSJGFJFSKEGKGSEHIIGLILSIJEF@A@@@IGCCFPKHIMECBBDEBFGIFGFGHDDDNFD??E((33AC=78.))*32333/,....CCDBCEEGJHSIJGKFGHDAAB????BDFDEDDFIHK:HIMSPDDJSJHSSJSSKIKSHEF>=91>>>?MFHJDAAA<755568=;??CBBCJIHFGF32222@?@?>;=<=>JSHSKJSIMIOMSMIISFFHQSKQNJHEIKSISFEDEFKMSKMLHSSQLGSKIFIHDESBKFHIIMQSIGIDFECFHJHLSIPFKGSGGSFEHILOJLQFMHLKQOGSJDFEFDJHEKJJHQGIFHFOSKGFA?..099FJSNIFEIISIMFHHIF33../('(((8CFCDDEBJEPKSNSSGGHMSJSGSOHSSF;FHS=KHGSHFQJHDJDGLFFGNMLFIGMFIJJB>>@??FFPIIGLGNHIKKGMKIJNHMKJFJMMSGGMGILOLHIFKNJFHJMSJKFSKSH@987AEDJSLJRIOLGIHSSOJSNHSLFPILFFEGJEFFDGDHJNLEO+++++711;EIQJHKSGIFJGGJGPSJJJHSLGKGEGECEEEGHKIHIHSLSBFJHMGFSIISSSHMMHFDCCCHBCB?=>?>?@>>>@CBBK>>7677.--&''%$%'&&&''(3?@???>?AABDA;@????@EFDEDBA?>=>=>?@?@=<<==ABAAABFCCCAB>>>?A.....DEIEHKFCCCC@AA?@AAGIFC==>=GFFD=;98899;?@?;;;;::::;?A55554CG@@:655499:=>DCFHQGSSREHNIEECDI612FCEDDMBAA@@@ACGCBC?@AA@?>>66777.-----,-??C>>>>=?>>>@@A>?>>>BCE;AA@@A@=;<6D*********>=:99899::;<?;888999?@??@@?BAB?@@?@?>>?>?@A;:::;??;;::;>?B<<<<=??>>@BD==<<<>>==>@ABAA@ABDAB@?<;<;;<==?>>@@=>>=:;::9;;<=>>>?=<<==<;=;:::89999:;;<A=>=>?@=<<<<<<<<=A
The fastq is right formated.

**Comment by MaestSi** [comment]
Hi, NanoFilt is complaining that the fastq file is not right formatted, despite the few reads you are showing seem to be ok. I'd suggest running that command outside of the pipeline and see if the error is reproducible, trying other sanity checks on the file (e.g. try compressing it, or aligning it).
SM

**Comment by MAXINELSX** [comment]
And also the last step I created issue for the cutadpter， I believe it is that if [[ -f "/autofs/tong1/LSX/lishuxian/lishuxian/test_data/output/primersTrimming/test_reads/test_reads_consensus_polished.fasta" ]]; then
    cutadapt -j 4 -e 0       --discard-untrimmed --match-read-wildcards       -g AGRGTTYGATYMTGGCTCAG -g $RV_primer_R        -a CGACATCGAGGTGCCAAAC -a $FW_primer_R       -m 3000 -M 6000       -o /autofs/tong1/LSX/lishuxian/lishuxian/test_data/output/primersTrimming/test_reads/test_reads_consensus_polished_primersTrimmed.fasta       /autofs/tong1/LSX/lishuxian/lishuxian/test_data/output/primersTrimming/test_reads/test_reads_consensus_polished.fasta
cannot recognize the  -g $RV_primer_R     and $FW_primer_R   properly

**Comment by MAXINELSX** [comment]
> Hi, NanoFilt is complaining that the fastq file is not right formatted, despite the few reads you are showing seem to be ok. I'd suggest running that command outside of the pipeline and see if the error is reproducible, trying other sanity checks on the file (e.g. try compressing it, or aligning it). SM
For this I tried https://github.com/SorenKarst/longread_umi/tree/master with the fastq, only medaka failed

**Comment by MaestSi** [comment]
> And also the last step I created issue for the cutadpter， I believe it is that if [[ -f "/autofs/tong1/LSX/lishuxian/lishuxian/test_data/output/primersTrimming/test_reads/test_reads_consensus_polished.fasta" ]]; then cutadapt -j 4 -e 0 --discard-untrimmed --match-read-wildcards -g AGRGTTYGATYMTGGCTCAG -g $RV_primer_R -a CGACATCGAGGTGCCAAAC -a $FW_primer_R -m 3000 -M 6000 -o /autofs/tong1/LSX/lishuxian/lishuxian/test_data/output/primersTrimming/test_reads/test_reads_consensus_polished_primersTrimmed.fasta /autofs/tong1/LSX/lishuxian/lishuxian/test_data/output/primersTrimming/test_reads/test_reads_consensus_polished.fasta cannot recognize the -g $RV_primer_R and $FW_primer_R properly

No, that is not an issue, I have the $FW_primer_R and $RV_primer_R too, in my succeeded runs.

**Comment by MaestSi** [comment]
> Hi, NanoFilt is complaining that the fastq file is not right formatted, despite the few reads you are showing seem to be ok. I'd suggest running that command outside of the pipeline and see if the error is reproducible, trying other sanity checks on the file (e.g. try compressing it, or aligning it). SM
> For this I tried https://github.com/SorenKarst/longread_umi/tree/master with the fastq, only medaka failed

Try running the following:
```
docker run -v /autofs/tong1/LSX/lishuxian/lishuxian/202403-UMI-16S/:/autofs/tong1/LSX/lishuxian/lishuxian/202403-UMI-16S/ --rm -ti maestsi/uminator:latest
zless /autofs/tong1/LSX/lishuxian/lishuxian/202403-UMI-16S/fastq/UASB_Nanopore.fastq | /opt/conda/envs/UMInator_env/bin/NanoFilt -q 7 --length 600 --maxlength 2000 > /autofs/tong1/LSX/lishuxian/lishuxian/202403-UMI-16S/fastq/UASB_Nanopore/readsFiltering/UASB_Nanopore/UASB_Nanopore_filtered.fastq
```
Let me know if that gives any errors, I'd expect so.
SM

**Comment by MAXINELSX** [comment]
> No, that is no

Noted, then I am not sure why.

**Comment by MAXINELSX** [comment]
![1712803584284](https://github.com/MaestSi/UMInator/assets/94595209/74e6aa77-dde9-415d-a724-e99af3996245)
Hii, sorry for the late reply, but this doesn't give errors.

**Comment by MaestSi** [comment]
I see, then it can only be an issue due to the resources you gave the process. The code you just ran is exactly what is run by the Nextflow pipeline, with the same software version. Please try increasing the RAM memory for that process and see if it succeeds. I do not have any further suggestions to give you.
SM

**Comment by MaestSi** [comment]
Hi, I'm going to close the issue due to inactivity. Feel free to reopen it, in case you have any further issues.
SM
