### ISSUE TITLE
medaka model

### ISSUE THREAD

**Issue by nic-ong** [MaestSi/UMInator#7]
Hi, thank you for creating this UMInator tool - I've had trouble with Karst's [longread_umi pipeline](https://github.com/SorenKarst/longread_umi/) and that sadly hasn't been maintained/updated since 2020, while yours has worked really well.

Could I please make a request though? The latest medaka version release is now v1.12.0, and I would like to use the more recent dorado basecaller models (sup v5.0) on my R10.4.1 nanopore data with your UMInator tool. Unfortunately, I noticed that the medaka package bundled in your docker image (`maestsi/uminator`) at the moment is v1.9.1, which only includes up to the v4.2.0 basecaller models e.g. r1041_e82_400bps_sup_v4.2.0. 

If you could push out an updated docker image with the latest medaka version whenever you have the bandwidth, that would be much appreciated! :)

Thank you very much!
Cheers,
nic-ong

**Comment by MaestSi** [comment]
Hi, you should be able to find the updated docker image on DockerHub. Please let me know if you are able to download it and run the pipeline.
Best,
SM

**Comment by nic-ong** [comment]
Hi, thanks for your incredible responsiveness! I could pull your updated docker image with `medaka v1.12.0` and ran UMInator successfully with a more recent medaka model `r1041_e82_400bps_sup_v4.3.0`! 
Much appreciated!
