### ISSUE TITLE
Feature to add umi_binning_stats file?

### ISSUE THREAD

**Issue by laulambr** [MaestSi/UMInator#9]
Hi

For most of my analysis on UMI based data I used the original pipeline on which this nextflow one is based (https://github.com/SorenKarst/longread_umi).
One of the more interesting outputs in that code was the "umi_binning_stats.txt" file, that was quite usefull when QC'ing runs, as it listed the metrics (coverage, chimera check, final filter decisions etc) per detected UMI pair. Such a file is missing from the new nextflow pipeline but I am wondering if such file could be incorporated as feature?

**Comment by MaestSi** [comment]
Hi,
indeed, most of the information you are referring to is printed to stdout by the **readsUMIsAssignment** process (**Filter_UMIs.R** script, specifically), although only at the aggregate level. Unfortunately, it is not saved to file, but you should be able to find the relevant information in the *.command.out* file, which you can find in the *work* directory of the **readsUMIsAssignment** process. For example:
```
Filtering out 15 UMIs, due to NM not satisfying conditions
Filtering out 18 UMIs, due to NM not satisfying conditions
Filtering out 26 reads, due to different best match for UMI1 and UMI2
```
Moreover, during the **QC** process, a text file named *<sample_name>_UMI_stats.tsv* is generated, reporting the number of reads supporting each UMI, and **NanoPlot** is run on the two sets of reads, i.e those that were assigned to a UMI and those that were not.
For the moment, I am not planning to add any additional QC steps, but I may consider doing that in the future.
Best,
SM

**Comment by MaestSi** [comment]
Closing the issue.
Best,
SM
